name: Automatic_Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Generating_Documentation:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Cache_doc
      id: cache-doc
      uses: actions/cache@v2
      with:
        path: temp-doc
        key: ${{ runner.os }}-doc
      
    - name: Change Directory 
      run: cd D:/a/Alis/Alis/ApiDoc
      
    - name: Show Directory 
      run: dir
      
    - name: Build Doc
      run: D:/a/Alis/Alis/ApiDoc/Doxygen/run/doxygen D:/a/Alis/Alis/ApiDocConfig
    
    - name: Update web
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git config core.autocrlf false
         git add .
         git commit -m "generated automatic documentation by actions"
         git push
        
